GET http://localhost:3000/recipes/  

###

GET http://localhost:3000/recipes/63f36f8f45b23599404642f8

###

POST http://localhost:3000/recipes
Content-Type: application/json

{
    "name": "hello",
    "time": 3,
    "ingredients": ["marv", "gamer"],
    "method": "Cook the marv and get the gamer"
}