GET http://localhost:3000/recipes  

###

GET http://localhost:3000/recipes/63f359a16ea33b1b1082b3b4

###

POST http://localhost:3000/recipes
Content-Type: application/json

{
    "name": "maybe",
    "time": 3,
    "ingredients": ["marv", "gamer"],
    "method": "Cook the marv and get the gamer"
}